### PR TITLE
Add text replacement example

### PR DESCRIPTION
**Pull request by agude**
Taken from:

https://sylvaindurand.org/improving-typography-on-jekyll/

### CODE REVIEW

**Comment by charles-uno** [comment]
Seems like we're working really hard to not use `skills` and ~~aspects~~

I thought we were ok with overloading markdown syntax?

**Review by charles-uno — COMMENTED** [review]
.

**Comment by agude** [comment]
I'm happy-ish with overloading; if we can make it easy `<spans>` are far superior because then we're not abusing the semantic HTML tags (since `<del>` litterally means "I've removed this text" but we're using it to mean "This is an aspect").

**Comment by agude** [comment]
I have created **completely** backwards compatable text replacement:

`~~Aspect~~` -> `<span class="aspect">Aspect</span>`

And

`` `Skill` `` -> `<span class="skill">Skill</span>`

**Pull request merged**
